### PR TITLE
Sync backend

### PR DESCRIPTION
**Pull request by goojal**
Hi!
This is a submission for the [this](https://gitcoin.co/issue/dfinance-tech/sync/1/100026637) bounty on gitcoin.

The code reads canisters info from config file and spawns a tokio task for each canister to periodically sync canister data to specified db.
I couldn't find any docs about the query limits. So I assumed they all work with previously set values (`QUERY_NUM = 100` and `QUERY_NUM_S = 13000`).
Tested with my own identity key and it works well, but changed the `KEY_PATH` to what it was before.
I removed the part of code which gets the `begin` parameter from env args and set it to `0` everytime for each canister. Let me know if you like to handle it another way.

It doesn't work for these 2 canisters:
1. token canister with id `42vp6-2iaaa-aaaah-qbooa-cai`. Because it has a slightly different candid than the token candid provided. It has an additional field (`burn: nat64`) in `Operation` type. So it can't be decoded.
2. dsawp-storage canister with id `4bqt3-aqaaa-aaaah-qbomq-cai`. Because there seems to be a problem with its `getTransactions` service. I even checked it in Candid UI and it shows this error:
`Call was rejected:
Request ID: 0cd71497fe889f546036010d150df05956aff43dacb80fe7db5f07882a604c3b
Reject code: 
Reject text: Canister 4bqt3-aqaaa-aaaah-qbomq-cai trapped explicitly: assertion failed at /Users/cyan/Desktop/blockchain/dfn/dfinance/backend-monorepo/dswap/src/storage.mo:243.9-243.46`
But, I tested the code with the dswap-storage canister which was already in the code (`gsf2f-kaaaa-aaaah-qaj4q-cai`). Tested the code with its `getHistory` service and it works well. It should work for the other one too because response types are the same.

Let me know if you need anything else! :hand:

### CODE REVIEW

**Comment by goojal** [comment]
Added a new canister type (token-burn) which supports the new candid type.
Also added the historySize check you mentioned for getTransactions.

**Comment by goojal** [comment]
Removed so many duplicated codes.

Now database info is implemented as trait for each of the types and there is only one `save_to_db` function which takes generic parameters. Also, extracted canister method calls as functions.

Resolved warnings and ran `cargo fmt`. Code is much cleaner now! :tada:

**Comment by ccyanxyz** [comment]
Great, I just made some minor changes to some struct names, can you make sure it compiles?

**Comment by goojal** [comment]
Fixed some little problems. It compiles now.

**Pull request merged**
